title: "Jayna's Data + Design Portfolio"
format:
  html:
    theme: lux
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true
website:
  title: "Jayna Snyder"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/jsnyder82
      - icon: linkedin
        href: https://linkedin.com/in/jayna-snyder
  page-footer:
    left: "© 2025 Jayna Snyder"
    right: "Built with ❤ + [Quarto](https://quarto.org)"
    
project:
    type: website
    output-dir: _site
    render:
    - index.qmd
    - projects.qmd
    - blog.qmd
    - projects/COPD_gene_project.qmd
    - projects/dimo_abstract.qmd

